namespace JaygahYar.Application.DTOs;

public record TankMonitoringInstallationFormDto(
    Guid Id,
    string FormNumber,
    DateTime? FormDate,
    string BuyerFullName,
    Guid StationId,
    string? StationAddress,
    string? Mobile,
    int GasolineTankCount,
    int DieselTankCount,
    DateTime? DeviceInstallationDate,
    DateTime? DeviceCommissioningDate,
    string? DeviceType,
    string? DisplaySerialNumber,
    string? PowerSerialNumber,
    bool DisplayPowerInstalledCorrectly,
    bool SuitableCableUsed,
    bool ProbesInstalledCorrectly,
    bool JunctionBoxInstalledCorrectly,
    bool CableEntryGasTight,
    bool FloatsInstalledCorrectly,
    bool ConsoleGroundAndProtectionUsed,
    bool SoftwarePurchased,
    bool SoftwareSetupPerformed,
    bool TankInfoMatchesDipstick,
    bool TrainingProvided,
    string? StationManagerName,
    List<ProbeItemDto> ProbeItems,
    DateTime CreatedAt
);

public record CreateTankMonitoringInstallationFormRequest(
    string FormNumber,
    DateTime? FormDate,
    string BuyerFullName,
    Guid StationId,
    string? StationAddress,
    string? Mobile,
    int GasolineTankCount,
    int DieselTankCount,
    DateTime? DeviceInstallationDate,
    DateTime? DeviceCommissioningDate,
    string? DeviceType,
    string? DisplaySerialNumber,
    string? PowerSerialNumber,
    bool DisplayPowerInstalledCorrectly,
    bool SuitableCableUsed,
    bool ProbesInstalledCorrectly,
    bool JunctionBoxInstalledCorrectly,
    bool CableEntryGasTight,
    bool FloatsInstalledCorrectly,
    bool ConsoleGroundAndProtectionUsed,
    bool SoftwarePurchased,
    bool SoftwareSetupPerformed,
    bool TankInfoMatchesDipstick,
    bool TrainingProvided,
    string? StationManagerName,
    List<CreateProbeItemRequest> ProbeItems
);
