// <auto-generated />
using System;
using JaygahYar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JaygahYar.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208054639_UpdateFormsToUploadBased")]
    partial class UpdateFormsToUploadBased
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("JaygahYar")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JaygahYar.Domain.Entities.AfterSalesServiceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<bool>("BarrierPlaced")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ContactDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("ContactTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DefectResolutionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("DefectResolutionTime")
                        .HasColumnType("interval");

                    b.Property<string>("DefectsReportedByCustomer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeviceCommissioningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DevicePowerCutOff")
                        .HasColumnType("boolean");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("numeric");

                    b.Property<string>("Downtime")
                        .HasColumnType("text");

                    b.Property<string>("ElectronicSystemType")
                        .HasColumnType("text");

                    b.Property<string>("ExpertOpinion")
                        .HasColumnType("text");

                    b.Property<bool>("FireExtinguisherNearby")
                        .HasColumnType("boolean");

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("GrandTotalInWords")
                        .HasColumnType("text");

                    b.Property<bool>("IsWarranty")
                        .HasColumnType("boolean");

                    b.Property<string>("LandlineAndMobile")
                        .HasColumnType("text");

                    b.Property<bool>("LeakCheckAfterService")
                        .HasColumnType("boolean");

                    b.Property<bool>("OilCompanyApprovalRequired")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PerformanceSideA")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PerformanceSideB")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PerformanceSideC")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PerformanceSideD")
                        .HasColumnType("numeric");

                    b.Property<string>("PersonnelDispatch")
                        .HasColumnType("text");

                    b.Property<string>("ProvincialRepresentativeName")
                        .HasColumnType("text");

                    b.Property<string>("ProvincialRepresentativeSignature")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("RepairTechnicianName")
                        .HasColumnType("text");

                    b.Property<string>("RepairTechnicianSignature")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<bool>("ShutOffValveClosed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StationManagerName")
                        .HasColumnType("text");

                    b.Property<string>("StationManagerSignature")
                        .HasColumnType("text");

                    b.Property<decimal?>("TravelCost")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WarehouseReceipt")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("AfterSalesServiceReports", "JaygahYar");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.OilToolInstallationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CommissioningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeviceInstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstallationFormFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PeymanegarTestFormFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("OilToolInstallationForms", "JaygahYar");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.ServiceReportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AfterSalesServiceReportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefectivePartSerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewPartSerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AfterSalesServiceReportId");

                    b.ToTable("ServiceReportItems", "JaygahYar");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Stage2DeliveryForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeviceCommissioningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeviceInstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DispenserManufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedFormFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Stage2DeliveryForms", "JaygahYar");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Stage3DeliveryForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DeviceCommissioningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeviceInstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedFormFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Stage3DeliveryForms", "JaygahYar");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DieselTankCount")
                        .HasColumnType("integer");

                    b.Property<int>("GasolineTankCount")
                        .HasColumnType("integer");

                    b.Property<string>("Mobile")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Stations", "JaygahYar");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.TankMonitoringInstallationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeviceCommissioningDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeviceInstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplaySerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<int>("TankCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedFormFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("TankMonitoringInstallationForms", "JaygahYar");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.AfterSalesServiceReport", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.Station", "Station")
                        .WithMany("AfterSalesReports")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.OilToolInstallationForm", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.Station", "Station")
                        .WithMany("OilToolInstallations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.ServiceReportItem", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.AfterSalesServiceReport", "AfterSalesServiceReport")
                        .WithMany("ServiceItems")
                        .HasForeignKey("AfterSalesServiceReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AfterSalesServiceReport");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Stage2DeliveryForm", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.Station", "Station")
                        .WithMany("Stage2DeliveryForms")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Stage3DeliveryForm", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.Station", "Station")
                        .WithMany("Stage3DeliveryForms")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.TankMonitoringInstallationForm", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.Station", "Station")
                        .WithMany("TankMonitoringInstallations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.AfterSalesServiceReport", b =>
                {
                    b.Navigation("ServiceItems");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Station", b =>
                {
                    b.Navigation("AfterSalesReports");

                    b.Navigation("OilToolInstallations");

                    b.Navigation("Stage2DeliveryForms");

                    b.Navigation("Stage3DeliveryForms");

                    b.Navigation("TankMonitoringInstallations");
                });
#pragma warning restore 612, 618
        }
    }
}
