// <auto-generated />
using System;
using JaygahYar.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JaygahYar.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260205121606_InitialMig")]
    partial class InitialMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JaygahYar.Domain.Entities.AfterSalesServiceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BarrierPlaced")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ContactDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ContactTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DefectResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("DefectResolutionTime")
                        .HasColumnType("time");

                    b.Property<string>("DefectsReportedByCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeviceCommissioningDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DevicePowerCutOff")
                        .HasColumnType("bit");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Downtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElectronicSystemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpertOpinion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FireExtinguisherNearby")
                        .HasColumnType("bit");

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GrandTotalInWords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWarranty")
                        .HasColumnType("bit");

                    b.Property<string>("LandlineAndMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LeakCheckAfterService")
                        .HasColumnType("bit");

                    b.Property<bool>("OilCompanyApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PerformanceSideA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PerformanceSideB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PerformanceSideC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PerformanceSideD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PersonnelDispatch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvincialRepresentativeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvincialRepresentativeSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepairTechnicianName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepairTechnicianSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShutOffValveClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StationManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationManagerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TravelCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarehouseReceipt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("AfterSalesServiceReports");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.DispenserInstallationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentPerformanceC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentPerformanceD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DispenserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelTypeA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelTypeB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NozzleCount")
                        .HasColumnType("int");

                    b.Property<Guid>("OilToolInstallationFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OilToolInstallationFormId");

                    b.ToTable("DispenserInstallationItems");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.OilToolInstallationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CheckValveInstalledForMotorized")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CommissioningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeviceInstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FloatQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("FormCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstallerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstallerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepresentativeSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepresentativeStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ShutOffValveInstalledCorrectly")
                        .HasColumnType("bit");

                    b.Property<string>("StationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StationOwnerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationOwnerStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StationType")
                        .HasColumnType("int");

                    b.Property<bool>("SuitableGlandsForInputCables")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("OilToolInstallationForms");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.ProbeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProbeSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProbeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("TankMonitoringInstallationFormId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TankNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TankMonitoringInstallationFormId");

                    b.ToTable("ProbeItems");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.ServiceReportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AfterSalesServiceReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefectivePartSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewPartSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AfterSalesServiceReportId");

                    b.ToTable("ServiceReportItems");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Stage2DeliveryForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandCompanyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CutoffCount")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DispenserManufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DispenserModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DualWallHoseCount")
                        .HasColumnType("int");

                    b.Property<bool>("EquipmentInstalled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FormDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FourNozzleDispenserCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasReceivedItems")
                        .HasColumnType("bit");

                    b.Property<bool?>("MotorThreePhase")
                        .HasColumnType("bit");

                    b.Property<int?>("NozzleCount")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PipeSlopeTowardTank")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepresentativeSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Revision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeparatorCount")
                        .HasColumnType("int");

                    b.Property<int?>("SingleNozzleDispenserCount")
                        .HasColumnType("int");

                    b.Property<int?>("SinglePhaseMotorCount")
                        .HasColumnType("int");

                    b.Property<bool>("Stage2PipingInsideDispensers")
                        .HasColumnType("bit");

                    b.Property<bool>("Stage2TestApproved")
                        .HasColumnType("bit");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StationManagerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationOwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee1NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee2NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee3NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TrainingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TwoNozzleDispenserCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VacuumPumpCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Stage2DeliveryForms");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Stage3DeliveryForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandCompanyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CompressorHasOil")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CompressorMaxCurrentAmpere")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryCommissioningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DipHatchGasTightChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("DrainHoseCapGasTightChecked")
                        .HasColumnType("bit");

                    b.Property<bool>("FlameArresterInstalled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FormDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HPGaugePressureAfterStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HPGaugePressureBeforeStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasStage2Commissioning")
                        .HasColumnType("bit");

                    b.Property<decimal?>("InitialTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCommissioning")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelivery")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LPGaugePressureAfterStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LPGaugePressureBeforeStart")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ManualTakeoffBlockerInstalled")
                        .HasColumnType("bit");

                    b.Property<bool>("PVCalibrationCertificateOnCollector")
                        .HasColumnType("bit");

                    b.Property<bool>("PVValvesOperationChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepresentativeSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Revision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SecondaryTemperatureMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SendDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StationGroundToDeviceChecked")
                        .HasColumnType("bit");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StationManagerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationOwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ThermometerOffTempC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ThermometerOnTempC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TimeToSecondaryTempMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Trainee1Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee1NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee2NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee3Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainee3NationalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TrainingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VaporInletOutletValvesChecked")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Stage3DeliveryForms");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DieselTankCount")
                        .HasColumnType("int");

                    b.Property<int>("GasolineTankCount")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.TankMonitoringInstallationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorizedRepresentativeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorizedRepresentativeSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CableEntryGasTight")
                        .HasColumnType("bit");

                    b.Property<bool>("ConsoleGroundAndProtectionUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeviceCommissioningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeviceInstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DieselTankCount")
                        .HasColumnType("int");

                    b.Property<bool>("DisplayPowerInstalledCorrectly")
                        .HasColumnType("bit");

                    b.Property<string>("DisplaySerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FloatsInstalledCorrectly")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FormDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GasolineTankCount")
                        .HasColumnType("int");

                    b.Property<string>("JaygahYarManagementName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JaygahYarManagementSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("JunctionBoxInstalledCorrectly")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProbesInstalledCorrectly")
                        .HasColumnType("bit");

                    b.Property<bool>("SoftwarePurchased")
                        .HasColumnType("bit");

                    b.Property<bool>("SoftwareSetupPerformed")
                        .HasColumnType("bit");

                    b.Property<string>("StationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StationManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationManagerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SuitableCableUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("TankInfoMatchesDipstick")
                        .HasColumnType("bit");

                    b.Property<bool>("TrainingProvided")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("TankMonitoringInstallationForms");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.AfterSalesServiceReport", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.Station", "Station")
                        .WithMany("AfterSalesReports")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.DispenserInstallationItem", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.OilToolInstallationForm", "OilToolInstallationForm")
                        .WithMany("DispenserItems")
                        .HasForeignKey("OilToolInstallationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OilToolInstallationForm");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.OilToolInstallationForm", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.Station", "Station")
                        .WithMany("OilToolInstallations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.ProbeItem", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.TankMonitoringInstallationForm", "TankMonitoringInstallationForm")
                        .WithMany("ProbeItems")
                        .HasForeignKey("TankMonitoringInstallationFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TankMonitoringInstallationForm");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.ServiceReportItem", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.AfterSalesServiceReport", "AfterSalesServiceReport")
                        .WithMany("ServiceItems")
                        .HasForeignKey("AfterSalesServiceReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AfterSalesServiceReport");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Stage2DeliveryForm", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.Station", "Station")
                        .WithMany("Stage2DeliveryForms")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Stage3DeliveryForm", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.Station", "Station")
                        .WithMany("Stage3DeliveryForms")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.TankMonitoringInstallationForm", b =>
                {
                    b.HasOne("JaygahYar.Domain.Entities.Station", "Station")
                        .WithMany("TankMonitoringInstallations")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.AfterSalesServiceReport", b =>
                {
                    b.Navigation("ServiceItems");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.OilToolInstallationForm", b =>
                {
                    b.Navigation("DispenserItems");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.Station", b =>
                {
                    b.Navigation("AfterSalesReports");

                    b.Navigation("OilToolInstallations");

                    b.Navigation("Stage2DeliveryForms");

                    b.Navigation("Stage3DeliveryForms");

                    b.Navigation("TankMonitoringInstallations");
                });

            modelBuilder.Entity("JaygahYar.Domain.Entities.TankMonitoringInstallationForm", b =>
                {
                    b.Navigation("ProbeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
